RAID_CONFIG_KEY = "raid:{}"
QUEUE_CONFIG_KEY = "raid:{}:queue:{}"
QUEUE_KEY = "raid:{}:queue:{}:q"

QUEUE_CURRENT_USERS = "current_users"
QUEUE_SIZE = "size"
QUEUE_NAME = "name"
QUEUE_ACTIVE = "active"
QUEUE_PROGRESS = "in_progress"
QUEUE_PING_AFTER = "role_ping_after"

RAID_INIT = "created"  # Dummy insert key just to check if the raid has been setup
RAID_ANNOUNCEMENTCHANNEL = "channel"
RAID_SPAWN = "spawn"
RAID_COOLDOWN = "cd"
RAID_RESET = "reset"
RAID_COUNTDOWNMESSAGE = "countdown_message"
RAID_MANAGEMENT_ROLES = "management_roles"
RAID_CLAN_ROLES = "clan_roles"
RAID_TIMER_ROLES = "timer_roles"
RAID_REMINDED = "reminded"
