RAID_CONFIG_KEY = "raid:{}"
QUEUE_CONFIG_KEY = "raid:{}:queue:{}"
QUEUE_KEY = "raid:{}:queue:{}:q"

QUEUE_CURRENT_USERS = "current_users"
QUEUE_SIZE = "size"
QUEUE_NAME = "name"
QUEUE_ACTIVE = "active"
QUEUE_PROGRESS = "in_progress"
QUEUE_PING_AFTER = "role_ping_after"
QUEUE_PAUSED = "paused"
QUEUE_OPEN = "open"
QUEUE_AUTO_CLOSE = "autoclose"

RAID_INIT = "created"  # Dummy insert key just to check if the raid has been setup
RAID_ANNOUNCEMENTCHANNEL = "announcement_channel"
RAID_SPAWN = "spawn"
RAID_COOLDOWN = "cd"
RAID_RESET = "reset"
RAID_COUNTDOWNMESSAGE = "countdown_message"
RAID_MANAGEMENT_ROLES = "management_roles"
RAID_CLAN_ROLES = "clan_roles"
RAID_TIMER_ROLES = "timer_roles"
RAID_REMINDED = "reminded"
RAID_UNSET_REMINDER = "unset_reminder"

EFFICIENCY_KEY = "efficiency"
EFFICIENCY_BASE = "base"
EFFICIENCY_CARD_PERC = "card_perc"
EFFICIENCY_TRESHOLD1 = "treshold1"
EFFICIENCY_TRESHOLD2 = "treshold2"
EFFICIENCY_REDUCTION1 = "reduction1"
EFFICIENCY_REDUCTION2 = "reduction2"
EFFICIENCY_CARDS_TOTAL = "cards_total"
EFFICIENCY_LETHAL_BONUS = "lethal_bonus"

CMD_RESTRICTIONS_USER = "{}:restriction:user:{}"
CMD_RESTRICTIONS_ROLE = "{}:restriction:role:{}"
CMD_RESTRICTIONS_CHANNEL = "{}:restriction:channel:{}"

PPREFIX = "pprefix"
