"""
This type stub file was generated by pyright.
"""

import logging
from collections import namedtuple
from .client import Client
from .appinfo import AppInfo
from .user import ClientUser, Profile, User
from .emoji import Emoji, PartialEmoji
from .activity import *
from .channel import *
from .guild import Guild, SystemChannelFlags
from .relationship import Relationship
from .member import Member, VoiceState
from .message import Attachment, Message
from .asset import Asset
from .errors import *
from .calls import CallMessage, GroupCall
from .permissions import PermissionOverwrite, Permissions
from .role import Role
from .file import File
from .colour import Color, Colour
from .invite import Invite, PartialInviteChannel, PartialInviteGuild
from .widget import Widget, WidgetChannel, WidgetMember
from .object import Object
from .reaction import Reaction
from . import abc, opus, utils
from .enums import *
from .embeds import Embed
from .shard import AutoShardedClient
from .player import *
from .webhook import *
from .voice_client import VoiceClient
from .audit_logs import AuditLogChanges, AuditLogDiff, AuditLogEntry
from .raw_models import *

"""
Discord API Wrapper
~~~~~~~~~~~~~~~~~~~

A basic wrapper for the Discord API.

:copyright: (c) 2015-2019 Rapptz
:license: MIT, see LICENSE for more details.

"""
__title__ = 'discord'
__author__ = 'Rapptz'
__license__ = 'MIT'
__copyright__ = 'Copyright 2015-2019 Rapptz'
__version__ = '1.2.3'
VersionInfo = namedtuple('VersionInfo', 'major minor micro releaselevel serial')
version_info = VersionInfo(major=1, minor=2, micro=3, releaselevel='final', serial=0)
