"""
This type stub file was generated by pyright.
"""

"""
The MIT License (MIT)

Copyright (c) 2015-2019 Rapptz

Permission is hereby granted, free of charge, to any person obtaining a
copy of this software and associated documentation files (the "Software"),
to deal in the Software without restriction, including without limitation
the rights to use, copy, modify, merge, publish, distribute, sublicense,
and/or sell copies of the Software, and to permit persons to whom the
Software is furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS
OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER
DEALINGS IN THE SOFTWARE.
"""
class Permissions:
    """Wraps up the Discord permission value.

    The properties provided are two way. You can set and retrieve individual
    bits using the properties as if they were regular bools. This allows
    you to edit permissions.

    .. container:: operations

        .. describe:: x == y

            Checks if two permissions are equal.
        .. describe:: x != y

            Checks if two permissions are not equal.
        .. describe:: x <= y

            Checks if a permission is a subset of another permission.
        .. describe:: x >= y

            Checks if a permission is a superset of another permission.
        .. describe:: x < y

             Checks if a permission is a strict subset of another permission.
        .. describe:: x > y

             Checks if a permission is a strict superset of another permission.
        .. describe:: hash(x)

               Return the permission's hash.
        .. describe:: iter(x)

               Returns an iterator of ``(perm, value)`` pairs. This allows it
               to be, for example, constructed as a dict or a list of pairs.

    Attributes
    -----------
    value
        The raw value. This value is a bit array field of a 53-bit integer
        representing the currently available permissions. You should query
        permissions via the properties rather than using this raw value.
    """
    __slots__ = ...
    def __init__(self, permissions=...):
        self.value = ...
    
    def __eq__(self, other):
        ...
    
    def __ne__(self, other):
        ...
    
    def __hash__(self):
        ...
    
    def __repr__(self):
        ...
    
    def _perm_iterator(self):
        ...
    
    def __iter__(self):
        ...
    
    def is_subset(self, other):
        """Returns ``True`` if self has the same or fewer permissions as other."""
        ...
    
    def is_superset(self, other):
        """Returns ``True`` if self has the same or more permissions as other."""
        ...
    
    def is_strict_subset(self, other):
        """Returns ``True`` if the permissions on other are a strict subset of those on self."""
        ...
    
    def is_strict_superset(self, other):
        """Returns ``True`` if the permissions on other are a strict superset of those on self."""
        ...
    
    __le__ = ...
    __ge__ = ...
    __lt__ = ...
    __gt__ = ...
    @classmethod
    def none(cls):
        """A factory method that creates a :class:`Permissions` with all
        permissions set to ``False``."""
        ...
    
    @classmethod
    def all(cls):
        """A factory method that creates a :class:`Permissions` with all
        permissions set to True."""
        ...
    
    @classmethod
    def all_channel(cls):
        """A :class:`Permissions` with all channel-specific permissions set to
        ``True`` and the guild-specific ones set to ``False``. The guild-specific
        permissions are currently:

        - manage_guild
        - kick_members
        - ban_members
        - administrator
        - change_nickname
        - manage_nicknames
        """
        ...
    
    @classmethod
    def general(cls):
        """A factory method that creates a :class:`Permissions` with all
        "General" permissions from the official Discord UI set to ``True``."""
        ...
    
    @classmethod
    def text(cls):
        """A factory method that creates a :class:`Permissions` with all
        "Text" permissions from the official Discord UI set to ``True``."""
        ...
    
    @classmethod
    def voice(cls):
        """A factory method that creates a :class:`Permissions` with all
        "Voice" permissions from the official Discord UI set to ``True``."""
        ...
    
    def update(self, **kwargs):
        r"""Bulk updates this permission object.

        Allows you to set multiple attributes by using keyword
        arguments. The names must be equivalent to the properties
        listed. Extraneous key/value pairs will be silently ignored.

        Parameters
        ------------
        \*\*kwargs
            A list of key/value pairs to bulk update permissions with.
        """
        ...
    
    def _bit(self, index):
        ...
    
    def _set(self, index, value):
        ...
    
    def handle_overwrite(self, allow, deny):
        self.value = ...
    
    @property
    def create_instant_invite(self):
        """:class:`bool`: Returns ``True`` if the user can create instant invites."""
        ...
    
    @create_instant_invite.setter
    def create_instant_invite(self, value):
        ...
    
    @property
    def kick_members(self):
        """:class:`bool`: Returns ``True`` if the user can kick users from the guild."""
        ...
    
    @kick_members.setter
    def kick_members(self, value):
        ...
    
    @property
    def ban_members(self):
        """:class:`bool`: Returns ``True`` if a user can ban users from the guild."""
        ...
    
    @ban_members.setter
    def ban_members(self, value):
        ...
    
    @property
    def administrator(self):
        """:class:`bool`: Returns ``True`` if a user is an administrator. This role overrides all other permissions.

        This also bypasses all channel-specific overrides.
        """
        ...
    
    @administrator.setter
    def administrator(self, value):
        ...
    
    @property
    def manage_channels(self):
        """:class:`bool`: Returns ``True`` if a user can edit, delete, or create channels in the guild.

        This also corresponds to the "Manage Channel" channel-specific override."""
        ...
    
    @manage_channels.setter
    def manage_channels(self, value):
        ...
    
    @property
    def manage_guild(self):
        """:class:`bool`: Returns ``True`` if a user can edit guild properties."""
        ...
    
    @manage_guild.setter
    def manage_guild(self, value):
        ...
    
    @property
    def add_reactions(self):
        """:class:`bool`: Returns ``True`` if a user can add reactions to messages."""
        ...
    
    @add_reactions.setter
    def add_reactions(self, value):
        ...
    
    @property
    def view_audit_log(self):
        """:class:`bool`: Returns ``True`` if a user can view the guild's audit log."""
        ...
    
    @view_audit_log.setter
    def view_audit_log(self, value):
        ...
    
    @property
    def priority_speaker(self):
        """:class:`bool`: Returns ``True`` if a user can be more easily heard while talking."""
        ...
    
    @priority_speaker.setter
    def priority_speaker(self, value):
        ...
    
    @property
    def stream(self):
        """:class:`bool`: Returns ``True`` if a user can stream in a voice channel."""
        ...
    
    @stream.setter
    def stream(self, value):
        ...
    
    @property
    def read_messages(self):
        """:class:`bool`: Returns ``True`` if a user can read messages from all or specific text channels."""
        ...
    
    @read_messages.setter
    def read_messages(self, value):
        ...
    
    @property
    def send_messages(self):
        """:class:`bool`: Returns ``True`` if a user can send messages from all or specific text channels."""
        ...
    
    @send_messages.setter
    def send_messages(self, value):
        ...
    
    @property
    def send_tts_messages(self):
        """:class:`bool`: Returns ``True`` if a user can send TTS messages from all or specific text channels."""
        ...
    
    @send_tts_messages.setter
    def send_tts_messages(self, value):
        ...
    
    @property
    def manage_messages(self):
        """:class:`bool`: Returns ``True`` if a user can delete or pin messages in a text channel.

        .. note::

            Note that there are currently no ways to edit other people's messages.
        """
        ...
    
    @manage_messages.setter
    def manage_messages(self, value):
        ...
    
    @property
    def embed_links(self):
        """:class:`bool`: Returns ``True`` if a user's messages will automatically be embedded by Discord."""
        ...
    
    @embed_links.setter
    def embed_links(self, value):
        ...
    
    @property
    def attach_files(self):
        """:class:`bool`: Returns ``True`` if a user can send files in their messages."""
        ...
    
    @attach_files.setter
    def attach_files(self, value):
        ...
    
    @property
    def read_message_history(self):
        """:class:`bool`: Returns ``True`` if a user can read a text channel's previous messages."""
        ...
    
    @read_message_history.setter
    def read_message_history(self, value):
        ...
    
    @property
    def mention_everyone(self):
        """:class:`bool`: Returns ``True`` if a user's @everyone or @here will mention everyone in the text channel."""
        ...
    
    @mention_everyone.setter
    def mention_everyone(self, value):
        ...
    
    @property
    def external_emojis(self):
        """:class:`bool`: Returns ``True`` if a user can use emojis from other guilds."""
        ...
    
    @external_emojis.setter
    def external_emojis(self, value):
        ...
    
    @property
    def connect(self):
        """:class:`bool`: Returns ``True`` if a user can connect to a voice channel."""
        ...
    
    @connect.setter
    def connect(self, value):
        ...
    
    @property
    def speak(self):
        """:class:`bool`: Returns ``True`` if a user can speak in a voice channel."""
        ...
    
    @speak.setter
    def speak(self, value):
        ...
    
    @property
    def mute_members(self):
        """:class:`bool`: Returns ``True`` if a user can mute other users."""
        ...
    
    @mute_members.setter
    def mute_members(self, value):
        ...
    
    @property
    def deafen_members(self):
        """:class:`bool`: Returns ``True`` if a user can deafen other users."""
        ...
    
    @deafen_members.setter
    def deafen_members(self, value):
        ...
    
    @property
    def move_members(self):
        """:class:`bool`: Returns ``True`` if a user can move users between other voice channels."""
        ...
    
    @move_members.setter
    def move_members(self, value):
        ...
    
    @property
    def use_voice_activation(self):
        """:class:`bool`: Returns ``True`` if a user can use voice activation in voice channels."""
        ...
    
    @use_voice_activation.setter
    def use_voice_activation(self, value):
        ...
    
    @property
    def change_nickname(self):
        """:class:`bool`: Returns ``True`` if a user can change their nickname in the guild."""
        ...
    
    @change_nickname.setter
    def change_nickname(self, value):
        ...
    
    @property
    def manage_nicknames(self):
        """:class:`bool`: Returns ``True`` if a user can change other user's nickname in the guild."""
        ...
    
    @manage_nicknames.setter
    def manage_nicknames(self, value):
        ...
    
    @property
    def manage_roles(self):
        """:class:`bool`: Returns ``True`` if a user can create or edit roles less than their role's position.

        This also corresponds to the "Manage Permissions" channel-specific override.
        """
        ...
    
    @manage_roles.setter
    def manage_roles(self, value):
        ...
    
    @property
    def manage_webhooks(self):
        """:class:`bool`: Returns ``True`` if a user can create, edit, or delete webhooks."""
        ...
    
    @manage_webhooks.setter
    def manage_webhooks(self, value):
        ...
    
    @property
    def manage_emojis(self):
        """:class:`bool`: Returns ``True`` if a user can create, edit, or delete emojis."""
        ...
    
    @manage_emojis.setter
    def manage_emojis(self, value):
        ...
    


def augment_from_permissions(cls):
    ...

@augment_from_permissions
class PermissionOverwrite:
    r"""A type that is used to represent a channel specific permission.

    Unlike a regular :class:`Permissions`\, the default value of a
    permission is equivalent to ``None`` and not ``False``. Setting
    a value to ``False`` is **explicitly** denying that permission,
    while setting a value to ``True`` is **explicitly** allowing
    that permission.

    The values supported by this are the same as :class:`Permissions`
    with the added possibility of it being set to ``None``.

    Supported operations:

    +-----------+------------------------------------------+
    | Operation |               Description                |
    +===========+==========================================+
    | x == y    | Checks if two overwrites are equal.      |
    +-----------+------------------------------------------+
    | x != y    | Checks if two overwrites are not equal.  |
    +-----------+------------------------------------------+
    | iter(x)   | Returns an iterator of (perm, value)     |
    |           | pairs. This allows this class to be used |
    |           | as an iterable in e.g. set/list/dict     |
    |           | constructions.                           |
    +-----------+------------------------------------------+

    Parameters
    -----------
    \*\*kwargs
        Set the value of permissions by their name.
    """
    __slots__ = ...
    def __init__(self, **kwargs):
        ...
    
    def __eq__(self, other):
        ...
    
    def _set(self, key, value):
        ...
    
    def pair(self):
        """Returns the (allow, deny) pair from this overwrite.

        The value of these pairs is :class:`Permissions`.
        """
        ...
    
    @classmethod
    def from_pair(cls, allow, deny):
        """Creates an overwrite from an allow/deny pair of :class:`Permissions`."""
        ...
    
    def is_empty(self):
        """Checks if the permission overwrite is currently empty.

        An empty permission overwrite is one that has no overwrites set
        to ``True`` or ``False``.
        """
        ...
    
    def update(self, **kwargs):
        r"""Bulk updates this permission overwrite object.

        Allows you to set multiple attributes by using keyword
        arguments. The names must be equivalent to the properties
        listed. Extraneous key/value pairs will be silently ignored.

        Parameters
        ------------
        \*\*kwargs
            A list of key/value pairs to bulk update with.
        """
        ...
    
    def __iter__(self):
        ...
    


